openapi: 3.0.2
info:
  version: impl
  title: Myasthenia Gravis Medication Check
  description: Checks for medications which should not be given to patients with myasthenia gravis
servers:
  - url: /99999/icdscreen/impl
paths:
  /icdscreen:
    post:
      description: Myasthenia Gravis Medication Check
      operationId: icdscreen
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/druglist'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
      x-kgrid-activation:
        artifact: src/index.js
        adapter: JAVASCRIPT
        entry: icdscreen
components:
  schemas:
    druglist:
      required:
      - rxcuis
      - icd10
      properties:
        rxcuis:
          type: string
          example: "141963,856917,994226,197446,801958"
        icd10:
          type: string
          example: "G70.00,G10.00"
    output:
      required:
      - result
      properties:
        result:
          type: string
          example: >-
            {"result": {"conflict": true,"rxcuis": {"0": "141963"}},"info": {"ko": {"@id": "impl","@type": "koio:Implementation","identifier": "ark:/99999/icdscreen/impl","title": "Myasthenia Gravis Medication Check","hasServiceSpecification": "impl/service.yaml","@context": ["http://kgrid.org/koio/contexts/implementation.jsonld"]},"inputs": {"rxcuis": "141963,856917,994226,197446,801958","icd10": "G70.00,G10.00"}}}
    Error:
      required:
      - code
      - message
